name = "mica-reality-sync"
main = "simple-worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ARTIST_DATA"
id = "982b4941446546d9a05bf0d624945552"

[[kv_namespaces]]
binding = "SYNC_STATE"
id = "470fd2556d6f4e6f9c0898e7fa3b337c"

[[kv_namespaces]]
binding = "CHANGE_LOG"
id = "bf81b42a00c6465faf7919c1e5ece085"

# D1 Database - uncomment when created
# [[d1_databases]]
# binding = "DB"
# database_name = "mica-database"
# database_id = "mica-db-production"

[triggers]
crons = ["0 */6 * * *"] # Run every 6 hours

[[routes]]
pattern = "mica-reality.franzai.com/*"
zone_name = "franzai.com"

[vars]
ENVIRONMENT = "production"
MAX_CONCURRENT_SCRAPES = "10"
CONFIDENCE_THRESHOLD = "0.7"